### PR TITLE
add pvp-arena box to show different lists of the pvp-arena protocol

### PR DESCRIPTION
**Pull request by dersiedler1**

### CODE REVIEW

**Comment by AlfonZ42** [comment]
I got the following error when opening PVP arena.
```
TypeError: Cannot read property 'length' of undefined
    at Object.multisort (_helper.js?v=3.4.0.0:87)
    at Object.StartPvPArena (pvparena.js?v=3.4.0.0:131)
    at pvparena.js?v=3.4.0.0:163
```
The response causing it is in 
[PVPArenaService_getOverview-undefined_length.zip](https://github.com/mainIine/foe-helfer-extension/files/13721216/PVPArenaService_getOverview-undefined_length.zip). Player ids and names were sanitized, so hopefully you'll be still able to reproduce it.

**Comment by Beelzebob6666** [comment]
I have the same issue - probably the object is not correctly initialized

**Comment by Beelzebob6666** [comment]
maybe get rid of the your sorting?

the helper already has a sorting feature - sorting is done in the output only for this:
the <tr > containing the table heads needs class "sorter-header"
the <th> that you want to sort by number need class "is-number" - "is-text" should be presumed if nothing is given - you can give class "ascending/descending" if you want to set an initial sorting direction
when sorting numbers, the individual <td> need class "is-number" and data-value "data-number=[1-9]"
when sorting text, the individual <td> need "data-text=[a-z]" 

you can look up the "Motivate/Polish Helper"/"Moppelassitent" table as reference

**Comment by dersiedler1** [comment]
removed the helper sorting as it is done correctly with only the markers on the table. 

was an old relict when i havent got the sort working with the table only.

**Comment by Beelzebob6666** [comment]
Hi there - seems to essentially work now.

Two things:
- setting for showing the box is not used to prevent showing the box yet
- I personally do not like that you globally modify the prototype string for a single use case - maybe just add the replace function inline?

**Comment by AlfonZ42** [comment]
Opening the arena calls `PvPArena.Show()` which toggles the box. For me, toggling the box is the expected behaviour when it's used on a menu button (which also calls `<module>.Show()`), not when opening the the arena - I would expect it to open the box (if configured so), or refresh (when already open).

The `string.prototype.cleanup` seems to be taken from _production_ module (which also does that). In contrast, _guildfights_ module uses slightly different regexp `/[\W_ ]+/` (vs. `/[^a-zA-Z0-9]+/`) on each use and doesn't modify the string prototype. 
Maybe adding a new unified function to _helper_ module and using that would be appropriate?

**Comment by dersiedler1** [comment]
yes as @AlfonZ42 mentioned the String function was taken from the production.js and as the code formatter mentioned this should be outside any function i put it at the start of the file.

according to open/close box: it should open when you click on the pvp-arena tower.  it should do the same as if you open the market and the market filter opens.

**Comment by dersiedler1** [comment]
fixed the initial active tab which @AlfonZ42 mentioned

**Comment by Beelzebob6666** [comment]
what I meant in regards to the setting - no matter what state it has, the table will be shown when opening the Arena

**Comment by Beelzebob6666** [comment]
Thanks for your contribution!
I hopefully was not too hard on you 😅

**Comment by dersiedler1** [comment]
all good. hopefully the feature will be useful for many users

**Pull request merged**
