### PR TITLE
Filter Kits/Sets

### PR DESCRIPTION
**Pull request by ycram**
Missed the possibility to search for kits/sets/items so I just tried to implement it.

### CODE REVIEW

**Review by Beelzebob6666 — APPROVED** [review]

**Comment by Beelzebob6666** [comment]
Looks good - Thanks for your contribution!

I will only add a minor CSS change to the top-bar and add the german translation

One thing missing is the translation capability for the placeholder, but I guess the users will figure that out.

**Comment by Beelzebob6666** [comment]
Unfortunately I did not recognize that your request was for the master - as pull requests have to refer beta, I messed this one up.

I will update the beta with your changes manually.

**Comment by ycram** [comment]
Sorry for the inconvenience, didn't know it had to target beta instead. Didn't expect it to be accepted without further discussion/changes as I'm only starting to play with JS a bit. Glad it didn't seem so bad :D Thanks!

**Comment by Beelzebob6666** [comment]
Looked good and worked - that is what counts :D

Did not look like a first time code to me - guess you bring some experience from another coding language.

**Pull request merged**
