### PR TITLE
scaling without rendering

### PR DESCRIPTION
**Pull request by honza111**
map data stays at 1em(int)

### CODE REVIEW

**Comment by dsiekiera** [comment]
What exactly are these changes for? Please describe them and/or send screenshots.

**Comment by honza111** [comment]
Hi,
thank you for contacting me. Theese changes have no effect to standard
functions of the FoE Helper, but i am using my own script for city planning
and theese changes are making it a little bit easier to me.
here is the screenshot: https://prnt.sc/115f5kt
here is the script https://justpaste.it/9en6f

I would like to implement it all into my own version of FoE Helper
on github, but i am very new to the system and i am also a little bit lazy
with it.... :)
And also i have one question: the user Mainline, is it you or is it
your colleague?:)
Thank you very much
JM

**Comment by dsiekiera** [comment]
Yes, it's me, mainline.

I would like to summarise again: 
- your script zooms the complete window
- copies the content into a new div in which a mouseover function selects buildings
- a drag&drop event is initiated

Did I miss something else?

mainline

**Comment by honza111** [comment]
Are you asking about my script or about the changes i have suggested on
github?
The changes on github are very simle. I have just deleted all the scaling
stuff and let it scale by changing font-size(or line-height).
The script i have made is beeing loaded externally (pasting into browsers
console or using tampermonkey extension). I am not professional developer,
i have made it suit my needs. I can drag and drop buildings, i can select
group of buildings and drag them at once(using ctrl shit and alt when
onmouseout). I can flip them vertically and horizontally. I can save all
the data into a file and load it again by pasting the file data into Chrome
console. Its working in 2D and also 3D and there is possible to scale it
all, but there is a little problem because the map is beeing executed again
and again on each scale command. There is no problem with changing 2d/3d
mode. So thats only thing i have suggested. Just made the scaling work same
way like the changing 2d/3d is.

Greeting
JM

**Comment by mainIine** [comment]
After looking at your code I have to inform you that we will not adopt it. 
The Citymap module is only intended for a pure "overview". To edit the city, we have the city planner with all its functions on the website.

Furthermore, we make a strict distinction between whether customisation requests are for an individual or are useful for the whole community.

Nevertheless, I thank you for your efforts and hope that you will soon send us something again.

mainline

**Comment by honza111** [comment]
i completely understand, but i have only suggested to change the way of
scaling, not to adopt my city planner into a live version of foe helper.
Anyway thank you for all the work on the foe helper at all. Its a very good
tool and you are amazing developer.

by the way .....i know your time is expensive but i still have one question
when we are communicating. Could you help me somehow, or maybe even create
it on your own, how to import a map from Cultural Settlements like viking,
aztecs... and/or the extended minicity in the age of The Asteroid Belt and
Space Age Mars into the city overview window? :)

really appreciate
JM

**Pull request closed without merging**
